### ISSUE TITLE
swatcherが大量のメッセージを投げているので抑制したい

### ISSUE THREAD

**Issue by yousan** [yousan/swatcher#9]
![image](https://user-images.githubusercontent.com/561613/41216884-19e2610a-6d91-11e8-8b1e-d12446cf9ed8.png)

原因は下記のうちどちらかと思いますが、いかがでしょうか？

1. ftp系と相性が悪い
1. swatcherの多重起動

**Comment by yousan** [comment]
![image](https://user-images.githubusercontent.com/561613/41217157-f5946c3e-6d91-11e8-8c42-ee30f4ea9f19.png)


Oh...

**Comment by sa9sha9** [comment]
fix it
